### ISSUE TITLE
Ability to add additional ports

### ISSUE THREAD

**Issue by 42hub** [wilfred-dev/wilfred#112]
So yeah, i would like a feature where you are able to add / remove an extra port to each server,
since other plugins like dynmap needs another port for the webserver.
```
wilfred port <server-name> add <8124-misspelld-8123>
wilfred port <server-name> remove <8124>
wilfred port <server-name> add <8123-for-default-dynmap>
```

**Comment by vilhelmprytz** [comment]
Thanks for submitting this. Working on this right now.
