### ISSUE TITLE
Ease monitoring of servers

### ISSUE THREAD

**Issue by alvarlagerlof** [wilfred-dev/wilfred#23]
**Is your feature request related to a problem? Please describe.**
When running multiple servers, getting an overview of chat cpu load, memory usage, chat activity and player count is not possible without custom code. 

**Describe the solution you'd like**
A command that fills the screen and updates in real-time, similar to something like `top`.

**Describe alternatives you've considered**
There are web-based UIs for managing servers, but I want to be able to do it from the command line.

**Additional context**
None.

**Comment by VilhelmPrytz** [comment]
I think showing the player count from within the CLI is an interesting feature on it's own. Either way, I definitely agree that the CLI should have the option to display more detailed statistics (in a `top` like way).
