### ISSUE TITLE
Logo for Wilfred

### ISSUE THREAD

**Issue by vilhelmprytz** [wilfred-dev/wilfred#32]
Wilfred needs a logo.

**Comment by PontusLiedgren** [comment]
![wilfred logo](https://user-images.githubusercontent.com/56937734/74132880-b2f2b300-4be7-11ea-9240-b2d39ab7a17f.png)

**Comment by VilhelmPrytz** [comment]
@PontusLiedgren Thank you very much for your contribution. We'll look into this.

**Comment by PontusLiedgren** [comment]
> @PontusLiedgren Thank you very much for your contribution. We'll look into this.

This is just a preview of what may come. ;-D

**Comment by vilhelmprytz** [comment]
Thanks @alvarlagerlof for the logo.
