### ISSUE TITLE
Server namespaces

### ISSUE THREAD

**Issue by alvarlagerlof** [wilfred-dev/wilfred#33]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have different namespaces so that I can have different groups of servers

**Describe the solution you'd like**
I'd be nice if they are stored in different folders or be prefixed in the folder names. For the cli, you could have a command to switch current namespace and something like `-n` or `--namespace` to run a specific command in another namespace.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vilhelmprytz** [comment]
After thinking about this, I am not too sure this is necessary. The Wilfred local database and configuration files are stored in the user's data directory and the user's config directory respectively (e.g. `/home/vilhelm/.local/share/wilfred/wilfred.sqlite` and `/home/vilhelm/.config/wilfred/config.json`). This means that when you log in as another Unix user, it's practically the same thing as switching between two namespaces. Each Unix user can have their own configuration files and server folders, the other Unix user will never see any Wilfred servers than the ones created by the same user.

I will be closing this for now, but if you can come up with other reasons for why specific namespaces are useful, feel free to re-open it. I'd be happy to accept documentation changes where this is mentioned in the documentation.
