### ISSUE TITLE
Push package to snapcraft

### ISSUE THREAD

**Issue by vilhelmprytz** [wilfred-dev/wilfred#6]
Waiting for the `classic` confinement to be approved.

See the [forum thread](https://forum.snapcraft.io/t/request-for-classic-confinement-for-package-wilfred/14912).

**Comment by VilhelmPrytz** [comment]
I have decided not to wait for this to finish, `master` will build using `devmode` to the latest/edge channel on Snapcraft till this package has approval for the classic confinement.

**Comment by VilhelmPrytz** [comment]
Update: still waiting for classic confinement. A discussion regarding the implementation of the Docker snap and how my snap application could communicate with the Docker socket regardless if the user installed Docker via snap or manually is also ongoing.

**Comment by VilhelmPrytz** [comment]
The feature Wilfred requires is to be implemented in `snapd` version 2.44. See linked PR.

**Comment by vilhelmprytz** [comment]
Waiting for https://github.com/snapcore/snapd/pull/8789

**Comment by vilhelmprytz** [comment]
I have decided to not support Snap. It just doesn't work.
